ALL_ATTR:
- 5_o_Clock_Shadow
- Arched_Eyebrows
- Attractive
- Bags_Under_Eyes
- Bald
- Bangs
- Big_Lips
- Big_Nose
- Black_Hair
- Blond_Hair
- Blurry
- Brown_Hair
- Bushy_Eyebrows
- Chubby
- Double_Chin
- Eyeglasses
- Goatee
- Gray_Hair
- Heavy_Makeup
- High_Cheekbones
- Male
- Mouth_Slightly_Open
- Mustache
- Narrow_Eyes
- No_Beard
- Oval_Face
- Pale_Skin
- Pointy_Nose
- Receding_Hairline
- Rosy_Cheeks
- Sideburns
- Smiling
- Straight_Hair
- Wavy_Hair
- Wearing_Earrings
- Wearing_Hat
- Wearing_Lipstick
- Wearing_Necklace
- Wearing_Necktie
- Young
batch_size: 32
image_size: 256
learning_rate: 0.001
model_output_path: model
model_path: classifier_model/best_model.pth
n_attributes: 1
preprocess_save_directory: /home/mla/PROJET-MLA/dataset
processed_file: dataset
raw_attributes_file: /home/mla/PROJET-MLA/dataset/list_attr_celeba.txt
raw_img_directory: /home/mla/PROJET-MLA/dataset/img_align_celeba
target_attribute_list:
- Male
total_epochs: 1000
total_train_samples: 50000
